services:
  web:
    image: my-app:latest
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    deploy:
      restart_policy:
        condition: any

  updater:
        image: my-app:latest
        command: ["tail","-f","/dev/null"]
        volumes:
          - ./:/app
        deploy:
          restart_policy:
            condition: any

